on:
  push:
    branches: [ master ]

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2.1.0

    - name: export game
      uses: firebelley/godot-export@v1.3.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
