on:
  push:
    branches: [ master ]

jobs:
  export_game:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2.2.0

    - name: export game
      uses: firebelley/godot-export@v2.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/rc2/mono/Godot_v3.2.2-rc2_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.2/rc2/mono/Godot_v3.2.2-rc2_mono_export_templates.tpz
        relative_project_path: ./
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
